import { MetricServiceClient, protos } from "@google-cloud/monitoring";
import { createTtlCache } from "@rodrigo-barraza/utilities-library/cache";
import logger from "../utils/logger.ts";
import { GOOGLE_ANALYTICS_CREDENTIALS, GOOGLE_CLOUD_MONITORING_PROJECT_ID } from "../config.ts";

// ── Google Cloud API Discovery ────────────────────────────────────
// Every service with request traffic in the monitored projects appears
// on the dashboard — discovery is dynamic, not allowlisted. The metadata
// map below only enriches services we recognize with friendly names,
// categories, and consumer attribution; unknown services fall back to a
// derived display name so new APIs are never silently hidden.

interface GoogleCloudApiMetadata {
  displayName: string;
  category: string;
  consumer: string;
  documentationUrl: string;
}

const KNOWN_API_METADATA: Record<string, GoogleCloudApiMetadata> = {
  "generativelanguage.googleapis.com": {
    displayName: "Gemini API",
    category: "AI / LLM",
    consumer: "prism-service",
    documentationUrl: "https://ai.google.dev/gemini-api/docs",
  },
  "aiplatform.googleapis.com": {
    displayName: "Vertex AI API",
    category: "AI / LLM",
    consumer: "ad-hoc",
    documentationUrl: "https://cloud.google.com/vertex-ai/docs",
  },
  "places.googleapis.com": {
    displayName: "Places API (New)",
    category: "Maps & Location",
    consumer: "tools-service",
    documentationUrl: "https://developers.google.com/maps/documentation/places/web-service",
  },
  // Cloud Monitoring labels the Maps Platform backends without a product
  // prefix ("geocoding-backend.googleapis.com" etc.) — these are the real
  // resource.labels.service values, not the enablement names.
  "geocoding-backend.googleapis.com": {
    displayName: "Geocoding API",
    category: "Maps & Location",
    consumer: "tools-service",
    documentationUrl: "https://developers.google.com/maps/documentation/geocoding",
  },
  "static-maps-backend.googleapis.com": {
    displayName: "Static Maps API",
    category: "Maps & Location",
    consumer: "tools-service",
    documentationUrl: "https://developers.google.com/maps/documentation/maps-static",
  },
  "maps-backend.googleapis.com": {
    displayName: "Maps JavaScript API",
    category: "Maps & Location",
    consumer: "tools-service",
    documentationUrl: "https://developers.google.com/maps/documentation/javascript",
  },
  "airquality.googleapis.com": {
    displayName: "Air Quality API",
    category: "Environmental",
    consumer: "tools-service",
    documentationUrl: "https://developers.google.com/maps/documentation/air-quality",
  },
  "pollen.googleapis.com": {
    displayName: "Pollen API",
    category: "Environmental",
    consumer: "tools-service",
    documentationUrl: "https://developers.google.com/maps/documentation/pollen",
  },
  "customsearch.googleapis.com": {
    displayName: "Custom Search JSON API",
    category: "Search",
    consumer: "tools-service",
    documentationUrl: "https://developers.google.com/custom-search/v1",
  },
  "youtube.googleapis.com": {
    displayName: "YouTube Data API v3",
    category: "Media",
    consumer: "tools-service",
    documentationUrl: "https://developers.google.com/youtube/v3",
  },
  "calendar-json.googleapis.com": {
    displayName: "Google Calendar API",
    category: "Productivity",
    consumer: "tools-service",
    documentationUrl: "https://developers.google.com/calendar",
  },
  "analyticsdata.googleapis.com": {
    displayName: "GA4 Data API",
    category: "Analytics",
    consumer: "portal-service",
    documentationUrl: "https://developers.google.com/analytics/devguides/reporting/data/v1",
  },
};

// Traffic generated by using the GCP console or by the monitoring/logging
// pipeline itself — not by our applications. Excluded from the dashboard;
// exclusions with traffic are logged so nothing disappears silently.
const EXCLUDED_INFRASTRUCTURE_SERVICES = new Set<string>([
  "datalineage.googleapis.com",
  "dataplex.googleapis.com",
  "datacatalog.googleapis.com",
  "bigquery.googleapis.com",
  "bigqueryconnection.googleapis.com",
  "bigquerystorage.googleapis.com",
  "monitoring.googleapis.com",
  "logging.googleapis.com",
  "cloudtrace.googleapis.com",
  "clouderrorreporting.googleapis.com",
  "serviceusage.googleapis.com",
  "servicemanagement.googleapis.com",
  "cloudresourcemanager.googleapis.com",
  "iam.googleapis.com",
  "iamcredentials.googleapis.com",
  "sts.googleapis.com",
  "oauth2.googleapis.com",
  "cloudbilling.googleapis.com",
]);

const SERVICE_IDENTIFIER_PATTERN = /^[a-z0-9][a-z0-9.-]{0,200}$/;

/** "geocoding-backend.googleapis.com" → "Geocoding Backend" */
function prettifyServiceIdentifier(serviceIdentifier: string): string {
  const bareName = serviceIdentifier.replace(/\.googleapis\.com$/, "");
  return bareName
    .split(/[.-]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function resolveApiMetadata(serviceIdentifier: string): GoogleCloudApiMetadata {
  return (
    KNOWN_API_METADATA[serviceIdentifier] ?? {
      displayName: prettifyServiceIdentifier(serviceIdentifier),
      category: "Other",
      consumer: "unattributed",
      documentationUrl: `https://console.cloud.google.com/apis/api/${serviceIdentifier}/metrics`,
    }
  );
}

// ── Types ──────────────────────────────────────────────────────────

interface ApiUsageSummary {
  serviceIdentifier: string;
  displayName: string;
  category: string;
  consumer: string;
  documentationUrl: string;
  totalRequests: number;
  successRequests: number;
  errorRequests: number;
  errorRate: number;
  dailySeries: { date: string; requests: number }[];
}

interface CloudUsageSummaryResponse {
  services: ApiUsageSummary[];
  totalRequests: number;
  totalErrors: number;
  period: string;
  projectId: string;
  projectIds: string[];
  unreachableProjectIds: string[];
  fetchedAt: string;
}

interface TimeSeriesDataPoint {
  date: string;
  requests: number;
  successRequests: number;
  errorRequests: number;
}

interface CloudUsageTimeSeriesResponse {
  serviceIdentifier: string;
  displayName: string;
  series: TimeSeriesDataPoint[];
  period: string;
  fetchedAt: string;
}

// ── Cache ──────────────────────────────────────────────────────────

const usageCache = createTtlCache();
const CACHE_TTL_MILLISECONDS = 5 * 60 * 1000; // 5 minutes

// ── Period Parsing ─────────────────────────────────────────────────

function periodToDays(period: string): number {
  const match = period.match(/^(\d+)d$/);
  if (match) return parseInt(match[1], 10);
  return 30;
}

function periodToInterval(period: string) {
  const days = periodToDays(period);
  const endTime = new Date();
  const startTime = new Date(endTime.getTime() - days * 24 * 60 * 60 * 1000);

  return {
    startTime: { seconds: Math.floor(startTime.getTime() / 1000) },
    endTime: { seconds: Math.floor(endTime.getTime() / 1000) },
  };
}

// ── Service ────────────────────────────────────────────────────────

type MonitoringTimeSeries = protos.google.monitoring.v3.ITimeSeries[];

export default class GoogleCloudUsageService {
  private static monitoringClient: MetricServiceClient | null = null;
  private static cachedProjectIds: string[] | null = null;

  private static getClient(): { client: MetricServiceClient; projectIds: string[] } {
    if (GoogleCloudUsageService.monitoringClient && GoogleCloudUsageService.cachedProjectIds) {
      return {
        client: GoogleCloudUsageService.monitoringClient,
        projectIds: GoogleCloudUsageService.cachedProjectIds,
      };
    }

    if (!GOOGLE_ANALYTICS_CREDENTIALS) {
      throw new Error("GOOGLE_ANALYTICS_CREDENTIALS is not configured — cannot query Cloud Monitoring");
    }

    const decoded = Buffer.from(GOOGLE_ANALYTICS_CREDENTIALS, "base64").toString("utf-8");
    const credentials = JSON.parse(decoded);

    GoogleCloudUsageService.monitoringClient = new MetricServiceClient({
      credentials: {
        client_email: credentials.client_email,
        private_key: credentials.private_key,
      },
      projectId: credentials.project_id,
    });

    // GOOGLE_CLOUD_MONITORING_PROJECT_ID is a comma-separated list — our API
    // keys live in a different GCP project (gen-lang-client-…) than the
    // service account / GA4 project (rod-dev-…), and both carry API traffic.
    const configuredProjectIds = (GOOGLE_CLOUD_MONITORING_PROJECT_ID || "")
      .split(",")
      .map((projectId) => projectId.trim())
      .filter(Boolean);
    const projectIds = [...new Set(
      configuredProjectIds.length > 0 ? configuredProjectIds : [credentials.project_id as string],
    )];
    GoogleCloudUsageService.cachedProjectIds = projectIds;
    logger.success(`[CloudUsage] Monitoring client initialized — querying projects: ${projectIds.join(", ")}`);

    return {
      client: GoogleCloudUsageService.monitoringClient,
      projectIds,
    };
  }

  static isValidServiceIdentifier(serviceIdentifier: string): boolean {
    return SERVICE_IDENTIFIER_PATTERN.test(serviceIdentifier);
  }

  /**
   * Query one metric filter across every configured project, tolerating
   * per-project failures (e.g. the service account lacking monitoring.viewer
   * on a project) so one bad grant doesn't blank the whole dashboard.
   */
  private static async listTimeSeriesAcrossProjects(filter: string, period: string): Promise<{
    timeSeries: MonitoringTimeSeries;
    reachableProjectIds: string[];
    unreachableProjectIds: string[];
  }> {
    const { client, projectIds } = GoogleCloudUsageService.getClient();
    const interval = periodToInterval(period);

    const results = await Promise.allSettled(
      projectIds.map((projectId) =>
        client.listTimeSeries({
          name: client.projectPath(projectId),
          filter,
          interval,
          view: "FULL",
        }),
      ),
    );

    const timeSeries: MonitoringTimeSeries = [];
    const reachableProjectIds: string[] = [];
    const unreachableProjectIds: string[] = [];

    results.forEach((result, index) => {
      const projectId = projectIds[index];
      if (result.status === "fulfilled") {
        timeSeries.push(...result.value[0]);
        reachableProjectIds.push(projectId);
      } else {
        unreachableProjectIds.push(projectId);
        const reason = result.reason instanceof Error ? result.reason.message : String(result.reason);
        logger.warn(
          `[CloudUsage] Project ${projectId} unreachable (grant roles/monitoring.viewer to the service account?): ${reason}`,
        );
      }
    });

    return { timeSeries, reachableProjectIds, unreachableProjectIds };
  }

  static async getSummary(period = "30d"): Promise<CloudUsageSummaryResponse> {
    return usageCache.get(`cloud-usage:summary:${period}`, CACHE_TTL_MILLISECONDS, () =>
      GoogleCloudUsageService.computeSummary(period),
    );
  }

  private static async computeSummary(period: string): Promise<CloudUsageSummaryResponse> {
    // No service filter — discover everything with traffic, then classify.
    const { timeSeries, reachableProjectIds, unreachableProjectIds } =
      await GoogleCloudUsageService.listTimeSeriesAcrossProjects(
        `metric.type = "serviceruntime.googleapis.com/api/request_count"`,
        period,
      );

    // Aggregate per-service
    const serviceDataMap = new Map<
      string,
      {
        totalRequests: number;
        successRequests: number;
        errorRequests: number;
        dailyBuckets: Map<string, number>;
      }
    >();
    const excludedTotals = new Map<string, number>();

    for (const singleTimeSeries of timeSeries) {
      const serviceLabel = singleTimeSeries.resource?.labels?.service;
      if (!serviceLabel) continue;

      const responseCodeClass = singleTimeSeries.metric?.labels?.response_code_class;
      const isError =
        responseCodeClass === "4xx" || responseCodeClass === "5xx";

      if (EXCLUDED_INFRASTRUCTURE_SERVICES.has(serviceLabel)) {
        let excludedCount = 0;
        for (const point of singleTimeSeries.points || []) {
          excludedCount += Number(point.value?.int64Value || 0);
        }
        excludedTotals.set(serviceLabel, (excludedTotals.get(serviceLabel) || 0) + excludedCount);
        continue;
      }

      if (!serviceDataMap.has(serviceLabel)) {
        serviceDataMap.set(serviceLabel, {
          totalRequests: 0,
          successRequests: 0,
          errorRequests: 0,
          dailyBuckets: new Map(),
        });
      }

      const serviceData = serviceDataMap.get(serviceLabel)!;

      for (const point of singleTimeSeries.points || []) {
        const requestCount = Number(point.value?.int64Value || 0);
        serviceData.totalRequests += requestCount;

        if (isError) {
          serviceData.errorRequests += requestCount;
        } else {
          serviceData.successRequests += requestCount;
        }

        // Aggregate into daily buckets
        const pointTimestamp = point.interval?.endTime?.seconds;
        if (pointTimestamp) {
          const dateString = new Date(Number(pointTimestamp) * 1000)
            .toISOString()
            .slice(0, 10);
          serviceData.dailyBuckets.set(
            dateString,
            (serviceData.dailyBuckets.get(dateString) || 0) + requestCount,
          );
        }
      }
    }

    if (excludedTotals.size > 0) {
      const excludedSummary = [...excludedTotals.entries()]
        .map(([service, count]) => `${service}=${count}`)
        .join(", ");
      logger.info(`[CloudUsage] Excluded console/infra traffic: ${excludedSummary}`);
    }

    // Build response — only include services with actual usage
    const services: ApiUsageSummary[] = [];
    let grandTotalRequests = 0;
    let grandTotalErrors = 0;

    for (const [serviceIdentifier, serviceData] of serviceDataMap) {
      if (serviceData.totalRequests === 0) continue;

      const metadata = resolveApiMetadata(serviceIdentifier);
      const dailySeries = Array.from(serviceData.dailyBuckets.entries())
        .map(([date, requests]) => ({ date, requests }))
        .sort((first, second) => first.date.localeCompare(second.date));

      services.push({
        serviceIdentifier,
        displayName: metadata.displayName,
        category: metadata.category,
        consumer: metadata.consumer,
        documentationUrl: metadata.documentationUrl,
        totalRequests: serviceData.totalRequests,
        successRequests: serviceData.successRequests,
        errorRequests: serviceData.errorRequests,
        errorRate:
          serviceData.totalRequests > 0
            ? serviceData.errorRequests / serviceData.totalRequests
            : 0,
        dailySeries,
      });

      grandTotalRequests += serviceData.totalRequests;
      grandTotalErrors += serviceData.errorRequests;
    }

    // Sort by total requests descending
    services.sort((first, second) => second.totalRequests - first.totalRequests);

    const result: CloudUsageSummaryResponse = {
      services,
      totalRequests: grandTotalRequests,
      totalErrors: grandTotalErrors,
      period,
      projectId: reachableProjectIds.join(" + "),
      projectIds: reachableProjectIds,
      unreachableProjectIds,
      fetchedAt: new Date().toISOString(),
    };

    return result;
  }

  static async getTimeSeries(
    serviceIdentifier: string,
    period = "30d",
  ): Promise<CloudUsageTimeSeriesResponse> {
    if (!GoogleCloudUsageService.isValidServiceIdentifier(serviceIdentifier)) {
      throw new Error(`Invalid service identifier: ${serviceIdentifier}`);
    }

    return usageCache.get(
      `cloud-usage:timeseries:${serviceIdentifier}:${period}`,
      CACHE_TTL_MILLISECONDS,
      () => GoogleCloudUsageService.computeTimeSeries(serviceIdentifier, period),
    );
  }

  private static async computeTimeSeries(
    serviceIdentifier: string,
    period: string,
  ): Promise<CloudUsageTimeSeriesResponse> {
    const { timeSeries } = await GoogleCloudUsageService.listTimeSeriesAcrossProjects(
      `metric.type = "serviceruntime.googleapis.com/api/request_count" AND resource.labels.service = "${serviceIdentifier}"`,
      period,
    );

    // Aggregate into daily buckets by response code class
    const dailyBuckets = new Map<
      string,
      { requests: number; successRequests: number; errorRequests: number }
    >();

    for (const singleTimeSeries of timeSeries) {
      const responseCodeClass = singleTimeSeries.metric?.labels?.response_code_class;
      const isError =
        responseCodeClass === "4xx" || responseCodeClass === "5xx";

      for (const point of singleTimeSeries.points || []) {
        const requestCount = Number(point.value?.int64Value || 0);
        const pointTimestamp = point.interval?.endTime?.seconds;
        if (!pointTimestamp) continue;

        const dateString = new Date(Number(pointTimestamp) * 1000)
          .toISOString()
          .slice(0, 10);

        if (!dailyBuckets.has(dateString)) {
          dailyBuckets.set(dateString, {
            requests: 0,
            successRequests: 0,
            errorRequests: 0,
          });
        }

        const bucket = dailyBuckets.get(dateString)!;
        bucket.requests += requestCount;

        if (isError) {
          bucket.errorRequests += requestCount;
        } else {
          bucket.successRequests += requestCount;
        }
      }
    }

    const series: TimeSeriesDataPoint[] = Array.from(dailyBuckets.entries())
      .map(([date, values]) => ({ date, ...values }))
      .sort((first, second) => first.date.localeCompare(second.date));

    const result: CloudUsageTimeSeriesResponse = {
      serviceIdentifier,
      displayName: resolveApiMetadata(serviceIdentifier).displayName,
      series,
      period,
      fetchedAt: new Date().toISOString(),
    };

    return result;
  }
}

// Exported for tests only.
export const __internal = {
  KNOWN_API_METADATA,
  EXCLUDED_INFRASTRUCTURE_SERVICES,
  prettifyServiceIdentifier,
  resolveApiMetadata,
};
